# Generated by Django 5.2.13 on 2026-05-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_outfitfavorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='categoria',
            field=models.CharField(choices=[('Camiseta', 'Camiseta'), ('Pantalón', 'Pantalón'), ('Zapato', 'Zapato'), ('Accesorio', 'Accesorio')], max_length=50),
        ),
    ]
